# Generated by Django 3.2.16 on 2023-05-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
